# Generated by Django 2.1.4 on 2018-12-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=22)),
                ('password', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=100)),
                ('token', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=22)),
                ('last_name', models.CharField(max_length=22)),
                ('gender', models.SmallIntegerField(default='')),
                ('phone', models.CharField(default='000-000-0000', max_length=13)),
                ('city', models.CharField(max_length=22)),
                ('state', models.CharField(max_length=4)),
                ('day', models.SmallIntegerField(default='01')),
                ('month', models.SmallIntegerField(default='01')),
                ('year', models.SmallIntegerField(default='1920')),
                ('website', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Credential')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=9)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('commitment', models.TextField(null=True)),
                ('since_month', models.IntegerField()),
                ('since_year', models.IntegerField()),
                ('portfolio', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Credential')),
            ],
        ),
    ]
