# Generated by Django 2.1.4 on 2018-12-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=models.CharField(max_length=22),
        ),
    ]
